package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"errors"
	"fmt"
	"sort"
	"time"

	"github.com/warerastats/api/graph/model"
	"github.com/warerastats/models/models/enums"
	"go.mongodb.org/mongo-driver/v2/bson"
	"go.mongodb.org/mongo-driver/v2/mongo"
)

// AttackerCountry is the resolver for the attackerCountry field.
func (r *battleResolver) AttackerCountry(ctx context.Context, obj *model.Battle) (*model.Country, error) {
	return loadCountry(ctx, obj.AttackerCountryID)
}

// DefenderCountry is the resolver for the defenderCountry field.
func (r *battleResolver) DefenderCountry(ctx context.Context, obj *model.Battle) (*model.Country, error) {
	return loadCountry(ctx, obj.DefenderCountryID)
}

// AttackerRegion is the resolver for the attackerRegion field.
func (r *battleResolver) AttackerRegion(ctx context.Context, obj *model.Battle) (*model.Region, error) {
	return loadRegionP(ctx, obj.AttackerRegionID)
}

// DefenderRegion is the resolver for the defenderRegion field.
func (r *battleResolver) DefenderRegion(ctx context.Context, obj *model.Battle) (*model.Region, error) {
	return loadRegion(ctx, obj.DefenderRegionID)
}

// Damages is the resolver for the damages field.
func (r *battleResolver) Damages(ctx context.Context, obj *model.Battle, first *int32, after *string, side *enums.Side, userID *string) ([]*model.Damage, error) {
	bid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	before, err := cursorPtr(after)
	if err != nil {
		return nil, err
	}
	uid, err := oidArgPtr(userID)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Trackers.Damage.GetByBattlePaged(ctx, bid, before, limitOf(first, 50), side, uid)
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toDamage), nil
}

// TopDamage is the resolver for the topDamage field.
func (r *battleResolver) TopDamage(ctx context.Context, obj *model.Battle, limit *int32) ([]*model.DamageRanking, error) {
	bid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Trackers.Damage.AggregateBattleDamage(ctx, bid, limitOf(limit, 10))
	if err != nil {
		return nil, err
	}
	out := make([]*model.DamageRanking, len(rows))
	for i, a := range rows {
		out[i] = &model.DamageRanking{UserID: a.UserID.Hex(), TotalDamage: a.TotalDamage, BattleCount: int32(a.BattleCount)}
	}
	return out, nil
}

// Mus is the resolver for the mus field.
func (r *battleResolver) Mus(ctx context.Context, obj *model.Battle) ([]*model.Mu, error) {
	bid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	orders, err := r.Colls.Events.BattleOrderChange.MuOrdersByBattles(ctx, []bson.ObjectID{bid})
	if err != nil {
		return nil, err
	}
	seen := make(map[string]struct{}, len(orders))
	out := make([]*model.Mu, 0, len(orders))
	for _, o := range orders {
		hex := o.MuID.Hex()
		if _, dup := seen[hex]; dup {
			continue
		}
		seen[hex] = struct{}{}
		m, err := loadMu(ctx, hex)
		if err != nil {
			return nil, err
		}
		if m != nil {
			out = append(out, m)
		}
	}
	return out, nil
}

// OrderChanges is the resolver for the orderChanges field.
func (r *battleResolver) OrderChanges(ctx context.Context, obj *model.Battle, first *int32, after *string) ([]*model.BattleOrderChange, error) {
	bid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	before, err := cursorPtr(after)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Events.BattleOrderChange.ListByBattle(ctx, bid, before, limitOf(first, 20))
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toBattleOrderChange), nil
}

// DamageReports is the resolver for the damageReports field.
func (r *battleResolver) DamageReports(ctx context.Context, obj *model.Battle, from *time.Time, to *time.Time, entityKind *model.EntityKind, entityIds []string) ([]*model.BattleDamageReport, error) {
	if from != nil && to != nil {
		if err := enforceTimeWindow(ctx, *from, *to, reportTimeWindowDays); err != nil {
			return nil, err
		}
	}
	bid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	ids, err := oidList(entityIds)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Processed.Reports.BattleDamageReport.GetByBattle(ctx, bid, from, to, entityKindStr(entityKind), ids)
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toBattleDamageReport), nil
}

// Owner is the resolver for the owner field.
func (r *companyResolver) Owner(ctx context.Context, obj *model.Company) (*model.User, error) {
	return loadUser(ctx, obj.UserID)
}

// Region is the resolver for the region field.
func (r *companyResolver) Region(ctx context.Context, obj *model.Company) (*model.Region, error) {
	return loadRegion(ctx, obj.RegionID)
}

// Employees is the resolver for the employees field.
func (r *companyResolver) Employees(ctx context.Context, obj *model.Company) ([]*model.Employee, error) {
	cid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Trackers.Employee.GetByCompany(ctx, cid)
	if err != nil {
		return nil, err
	}
	return mapPtr(rows, toEmployee), nil
}

// RegionHistory is the resolver for the regionHistory field.
func (r *companyResolver) RegionHistory(ctx context.Context, obj *model.Company, first *int32, after *string) ([]*model.CompanyRegionChange, error) {
	cid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	before, err := cursorPtr(after)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Events.CompanyRegionChange.ListByCompany(ctx, cid, before, limitOf(first, 20))
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toCompanyRegionChange), nil
}

// ItemCodeHistory is the resolver for the itemCodeHistory field.
func (r *companyResolver) ItemCodeHistory(ctx context.Context, obj *model.Company, first *int32, after *string) ([]*model.CompanyItemCodeChange, error) {
	cid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	before, err := cursorPtr(after)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Events.CompanyItemCodeChange.ListByCompany(ctx, cid, before, limitOf(first, 20))
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toCompanyItemCodeChange), nil
}

// RulingParty is the resolver for the rulingParty field.
func (r *countryResolver) RulingParty(ctx context.Context, obj *model.Country) (*model.Party, error) {
	return loadPartyP(ctx, obj.RulingPartyID)
}

// Users is the resolver for the users field.
func (r *countryResolver) Users(ctx context.Context, obj *model.Country, first *int32, after *string) ([]*model.User, error) {
	cid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	before, err := cursorPtr(after)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Trackers.User.GetByCountryPaged(ctx, cid, before, limitOf(first, 20))
	if err != nil {
		return nil, err
	}
	return mapPtr(rows, toUser), nil
}

// UserCount is the resolver for the userCount field.
func (r *countryResolver) UserCount(ctx context.Context, obj *model.Country) (int32, error) {
	aggs, err := r.Colls.Trackers.User.CountByCountry(ctx)
	if err != nil {
		return 0, err
	}
	for _, a := range aggs {
		if a.CountryID.Hex() == obj.ID {
			return int32(a.MemberCount), nil
		}
	}
	return 0, nil
}

// Parties is the resolver for the parties field.
func (r *countryResolver) Parties(ctx context.Context, obj *model.Country, first *int32, after *string) ([]*model.Party, error) {
	cid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	before, err := cursorPtr(after)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Trackers.Party.GetByCountryPaged(ctx, cid, before, limitOf(first, 20))
	if err != nil {
		return nil, err
	}
	return mapPtr(rows, toParty), nil
}

// Regions is the resolver for the regions field.
func (r *countryResolver) Regions(ctx context.Context, obj *model.Country) ([]*model.Region, error) {
	cid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Trackers.Region.GetByCountry(ctx, cid)
	if err != nil {
		return nil, err
	}
	return mapPtr(rows, toRegion), nil
}

// Battles is the resolver for the battles field.
func (r *countryResolver) Battles(ctx context.Context, obj *model.Country, first *int32, after *string, filter *model.BattleFilter) ([]*model.Battle, error) {
	cid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	before, err := cursorPtr(after)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Trackers.Battle.GetByCountryPaged(ctx, cid, toBattleFilter(filter), before, limitOf(first, 20))
	if err != nil {
		return nil, err
	}
	return mapPtr(rows, toBattle), nil
}

// OrderChanges is the resolver for the orderChanges field.
func (r *countryResolver) OrderChanges(ctx context.Context, obj *model.Country, first *int32, after *string) ([]*model.BattleOrderChange, error) {
	cid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	before, err := cursorPtr(after)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Events.BattleOrderChange.ListByEntity(ctx, "country", cid, before, limitOf(first, 20))
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toBattleOrderChange), nil
}

// RulingPartyHistory is the resolver for the rulingPartyHistory field.
func (r *countryResolver) RulingPartyHistory(ctx context.Context, obj *model.Country, first *int32, after *string) ([]*model.CountryRulingPartyChange, error) {
	cid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	before, err := cursorPtr(after)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Events.CountryRulingPartyChange.ListByCountry(ctx, cid, before, limitOf(first, 20))
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toCountryRulingPartyChange), nil
}

// SpecialisationHistory is the resolver for the specialisationHistory field.
func (r *countryResolver) SpecialisationHistory(ctx context.Context, obj *model.Country, first *int32, after *string) ([]*model.CountrySpecialisationChange, error) {
	cid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	before, err := cursorPtr(after)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Events.CountrySpecialisationChange.ListByCountry(ctx, cid, before, limitOf(first, 20))
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toCountrySpecialisationChange), nil
}

// TaxFlows is the resolver for the taxFlows field.
func (r *countryResolver) TaxFlows(ctx context.Context, obj *model.Country, from time.Time, to time.Time) ([]*model.CountryTaxFlow, error) {
	if err := enforceTimeWindow(ctx, from, to, reportTimeWindowDays); err != nil {
		return nil, err
	}
	cid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Processed.Reports.CountryTaxFlow.GetByCountryRange(ctx, cid, from, to)
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toCountryTaxFlow), nil
}

// MoneyFlows is the resolver for the moneyFlows field.
func (r *countryResolver) MoneyFlows(ctx context.Context, obj *model.Country, from time.Time, to time.Time) ([]*model.CountryMoneyFlowReport, error) {
	if err := enforceTimeWindow(ctx, from, to, reportTimeWindowDays); err != nil {
		return nil, err
	}
	cid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Processed.Reports.CountryMoneyFlow.GetByCountryRange(ctx, cid, from, to)
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toCountryMoneyFlowReport), nil
}

// FlipEvents is the resolver for the flipEvents field.
func (r *countryResolver) FlipEvents(ctx context.Context, obj *model.Country, from time.Time, to time.Time, first *int32, after *string) ([]*model.CountryFlipEvent, error) {
	if err := enforceTimeWindow(ctx, from, to, rawTimeWindowDays); err != nil {
		return nil, err
	}
	cid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	before, err := cursorPtr(after)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Processed.Estimators.CountryFlipEvent.GetByCountryRange(ctx, cid, from, to, before, limitOf(first, 50))
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toCountryFlipEvent), nil
}

// FlipState is the resolver for the flipState field.
func (r *countryResolver) FlipState(ctx context.Context, obj *model.Country) (*model.CountryFlipState, error) {
	cid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	st, ok, err := r.Colls.Processed.Estimators.CountryFlipState.Get(ctx, cid)
	if err != nil || !ok {
		return nil, err
	}
	return toCountryFlipState(st), nil
}

// Inventory is the resolver for the inventory field.
func (r *countryResolver) Inventory(ctx context.Context, obj *model.Country) (*model.CountryInventory, error) {
	cid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	inv, ok, err := r.Colls.Processed.Estimators.CountryInventory.Get(ctx, cid)
	if err != nil || !ok {
		return nil, err
	}
	return toCountryInventory(inv), nil
}

// WealthReports is the resolver for the wealthReports field.
func (r *countryResolver) WealthReports(ctx context.Context, obj *model.Country, from time.Time, to time.Time) ([]*model.EntityWealthReport, error) {
	if err := enforceTimeWindow(ctx, from, to, reportTimeWindowDays); err != nil {
		return nil, err
	}
	cid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Processed.Reports.EntityWealthReport.GetByEntityRange(ctx, "country", cid, from, to)
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toEntityWealthReport), nil
}

// Battle is the resolver for the battle field.
func (r *damageResolver) Battle(ctx context.Context, obj *model.Damage) (*model.Battle, error) {
	return loadBattle(ctx, obj.BattleID)
}

// User is the resolver for the user field.
func (r *damageResolver) User(ctx context.Context, obj *model.Damage) (*model.User, error) {
	return loadUser(ctx, obj.UserID)
}

// Country is the resolver for the country field.
func (r *damageResolver) Country(ctx context.Context, obj *model.Damage) (*model.Country, error) {
	return loadCountry(ctx, obj.CountryID)
}

// Mu is the resolver for the mu field.
func (r *damageResolver) Mu(ctx context.Context, obj *model.Damage) (*model.Mu, error) {
	return loadMuP(ctx, obj.MuID)
}

// Party is the resolver for the party field.
func (r *damageResolver) Party(ctx context.Context, obj *model.Damage) (*model.Party, error) {
	return loadPartyP(ctx, obj.PartyID)
}

// Skill is not resolved: the skills collection has no by-id lookup; the snapshot
// id is exposed only as a relation placeholder. Returns null.
func (r *damageResolver) Skill(ctx context.Context, obj *model.Damage) (*model.Skill, error) {
	return nil, nil
}

// Weapon is the resolver for the weapon field.
func (r *damageResolver) Weapon(ctx context.Context, obj *model.Damage) (*model.Item, error) {
	return loadItemP(ctx, obj.WeaponID)
}

// Helmet is the resolver for the helmet field.
func (r *damageResolver) Helmet(ctx context.Context, obj *model.Damage) (*model.Item, error) {
	return loadItemP(ctx, obj.HelmetID)
}

// Chest is the resolver for the chest field.
func (r *damageResolver) Chest(ctx context.Context, obj *model.Damage) (*model.Item, error) {
	return loadItemP(ctx, obj.ChestID)
}

// Pants is the resolver for the pants field.
func (r *damageResolver) Pants(ctx context.Context, obj *model.Damage) (*model.Item, error) {
	return loadItemP(ctx, obj.PantsID)
}

// Boots is the resolver for the boots field.
func (r *damageResolver) Boots(ctx context.Context, obj *model.Damage) (*model.Item, error) {
	return loadItemP(ctx, obj.BootsID)
}

// Gloves is the resolver for the gloves field.
func (r *damageResolver) Gloves(ctx context.Context, obj *model.Damage) (*model.Item, error) {
	return loadItemP(ctx, obj.GlovesID)
}

// User is the resolver for the user field.
func (r *employeeResolver) User(ctx context.Context, obj *model.Employee) (*model.User, error) {
	return loadUser(ctx, obj.UserID)
}

// Company is the resolver for the company field.
func (r *employeeResolver) Company(ctx context.Context, obj *model.Employee) (*model.Company, error) {
	return loadCompany(ctx, obj.CompanyID)
}

// Employer is the resolver for the employer field.
func (r *employeeResolver) Employer(ctx context.Context, obj *model.Employee) (*model.User, error) {
	return loadUser(ctx, obj.EmployerID)
}

// WageHistory is the resolver for the wageHistory field.
func (r *employeeResolver) WageHistory(ctx context.Context, obj *model.Employee, first *int32, after *string) ([]*model.EmployeeWageChange, error) {
	uid, err := oidOf(obj.UserID)
	if err != nil {
		return nil, err
	}
	before, err := cursorPtr(after)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Events.EmployeeWageChange.ListByUser(ctx, uid, before, limitOf(first, 20))
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toEmployeeWageChange), nil
}

// Skills is the resolver for the skills field.
func (r *itemResolver) Skills(ctx context.Context, obj *model.Item) ([]*model.FloatEntry, error) {
	return floatEntries(obj.SkillsMap), nil
}

// Owner is the resolver for the owner field.
func (r *itemResolver) Owner(ctx context.Context, obj *model.Item) (*model.User, error) {
	return loadUser(ctx, obj.OwnerUserID)
}

// MarketTransactions is the resolver for the marketTransactions field.
func (r *itemResolver) MarketTransactions(ctx context.Context, obj *model.Item, first *int32, after *string) ([]*model.MarketTransaction, error) {
	iid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	before, err := cursorPtr(after)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Transactions.MarketTransaction.GetByItemPaged(ctx, iid, before, limitOf(first, 20))
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toMarket), nil
}

// Owner is the resolver for the owner field.
func (r *muResolver) Owner(ctx context.Context, obj *model.Mu) (*model.User, error) {
	return loadUser(ctx, obj.OwnerUserID)
}

// Region is the resolver for the region field.
func (r *muResolver) Region(ctx context.Context, obj *model.Mu) (*model.Region, error) {
	return loadRegion(ctx, obj.RegionID)
}

// Members is the resolver for the members field.
func (r *muResolver) Members(ctx context.Context, obj *model.Mu) ([]*model.User, error) {
	return r.loadMembers(ctx, obj.MemberUserIDs)
}

// Battles is the resolver for the battles field.
func (r *muResolver) Battles(ctx context.Context, obj *model.Mu, first *int32, after *string, filter *model.BattleFilter) ([]*model.Battle, error) {
	mid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	before, err := cursorPtr(after)
	if err != nil {
		return nil, err
	}
	ids, err := r.Colls.Events.BattleOrderChange.ListBattleIDsByMu(ctx, mid, before, limitOf(first, 20))
	if err != nil {
		return nil, err
	}
	want := toBattleFilter(filter)
	out := make([]*model.Battle, 0, len(ids))
	for _, id := range ids {
		b, err := loadBattle(ctx, id.Hex())
		if err != nil {
			return nil, err
		}
		if b == nil || !battleMatchesFilter(b, want) {
			continue
		}
		out = append(out, b)
	}
	return out, nil
}

// OrderChanges is the resolver for the orderChanges field.
func (r *muResolver) OrderChanges(ctx context.Context, obj *model.Mu, first *int32, after *string) ([]*model.BattleOrderChange, error) {
	mid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	before, err := cursorPtr(after)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Events.BattleOrderChange.ListByEntity(ctx, "mu", mid, before, limitOf(first, 20))
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toBattleOrderChange), nil
}

// NameHistory is the resolver for the nameHistory field.
func (r *muResolver) NameHistory(ctx context.Context, obj *model.Mu, first *int32, after *string) ([]*model.MuNameChange, error) {
	mid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	before, err := cursorPtr(after)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Events.MuNameChange.ListByMu(ctx, mid, before, limitOf(first, 20))
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toMuNameChange), nil
}

// OwnerHistory is the resolver for the ownerHistory field.
func (r *muResolver) OwnerHistory(ctx context.Context, obj *model.Mu, first *int32, after *string) ([]*model.MuOwnerChange, error) {
	mid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	before, err := cursorPtr(after)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Events.MuOwnerChange.ListByMu(ctx, mid, before, limitOf(first, 20))
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toMuOwnerChange), nil
}

// MercReputationHistory is the resolver for the mercReputationHistory field.
func (r *muResolver) MercReputationHistory(ctx context.Context, obj *model.Mu, first *int32, after *string) ([]*model.MuMercenaryReputationChange, error) {
	mid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	before, err := cursorPtr(after)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Events.MuMercenaryReputationChange.ListByMu(ctx, mid, before, limitOf(first, 20))
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toMuMercenaryReputationChange), nil
}

// WealthReports is the resolver for the wealthReports field.
func (r *muResolver) WealthReports(ctx context.Context, obj *model.Mu, from time.Time, to time.Time) ([]*model.EntityWealthReport, error) {
	if err := enforceTimeWindow(ctx, from, to, reportTimeWindowDays); err != nil {
		return nil, err
	}
	mid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Processed.Reports.EntityWealthReport.GetByEntityRange(ctx, "mu", mid, from, to)
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toEntityWealthReport), nil
}

// Country is the resolver for the country field.
func (r *partyResolver) Country(ctx context.Context, obj *model.Party) (*model.Country, error) {
	return loadCountry(ctx, obj.CountryID)
}

// Region is the resolver for the region field.
func (r *partyResolver) Region(ctx context.Context, obj *model.Party) (*model.Region, error) {
	return loadRegion(ctx, obj.RegionID)
}

// Leader is the resolver for the leader field.
func (r *partyResolver) Leader(ctx context.Context, obj *model.Party) (*model.User, error) {
	return loadUser(ctx, obj.LeaderUserID)
}

// Members is the resolver for the members field.
func (r *partyResolver) Members(ctx context.Context, obj *model.Party) ([]*model.User, error) {
	return r.loadMembers(ctx, obj.MemberUserIDs)
}

// RulesCountries is the resolver for the rulesCountries field.
func (r *partyResolver) RulesCountries(ctx context.Context, obj *model.Party) ([]*model.Country, error) {
	pid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Trackers.Country.GetByRulingParty(ctx, pid)
	if err != nil {
		return nil, err
	}
	return mapPtr(rows, toCountry), nil
}

// Battles is the resolver for the battles field.
func (r *partyResolver) Battles(ctx context.Context, obj *model.Party, first *int32, after *string) ([]*model.Battle, error) {
	pid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	before, err := cursorPtr(after)
	if err != nil {
		return nil, err
	}
	ids, err := r.Colls.Trackers.Damage.GetBattleIDsByPartyPaged(ctx, pid, before, limitOf(first, 20))
	if err != nil {
		return nil, err
	}
	out := make([]*model.Battle, 0, len(ids))
	for _, id := range ids {
		b, err := loadBattle(ctx, id.Hex())
		if err != nil {
			return nil, err
		}
		if b != nil {
			out = append(out, b)
		}
	}
	return out, nil
}

// Participation is the resolver for the participation field.
func (r *partyResolver) Participation(ctx context.Context, obj *model.Party) (*model.PartyBattleParticipation, error) {
	pid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	agg, err := r.Colls.Trackers.Damage.AggregatePartyParticipation(ctx, pid)
	if err != nil {
		return nil, err
	}
	return &model.PartyBattleParticipation{
		Party:       obj,
		TotalDamage: int(agg.TotalDamage),
		BattleCount: int32(agg.BattleCount),
	}, nil
}

// NameHistory is the resolver for the nameHistory field.
func (r *partyResolver) NameHistory(ctx context.Context, obj *model.Party, first *int32, after *string) ([]*model.PartyNameChange, error) {
	pid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	before, err := cursorPtr(after)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Events.PartyNameChange.ListByParty(ctx, pid, before, limitOf(first, 20))
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toPartyNameChange), nil
}

// LeaderHistory is the resolver for the leaderHistory field.
func (r *partyResolver) LeaderHistory(ctx context.Context, obj *model.Party, first *int32, after *string) ([]*model.PartyLeaderChange, error) {
	pid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	before, err := cursorPtr(after)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Events.PartyLeaderChange.ListByParty(ctx, pid, before, limitOf(first, 20))
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toPartyLeaderChange), nil
}

// DescriptionHistory is the resolver for the descriptionHistory field.
func (r *partyResolver) DescriptionHistory(ctx context.Context, obj *model.Party, first *int32, after *string) ([]*model.PartyDescriptionChange, error) {
	pid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	before, err := cursorPtr(after)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Events.PartyDescriptionChange.ListByParty(ctx, pid, before, limitOf(first, 20))
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toPartyDescriptionChange), nil
}

// EthicsHistory is the resolver for the ethicsHistory field.
func (r *partyResolver) EthicsHistory(ctx context.Context, obj *model.Party, first *int32, after *string) ([]*model.PartyEthicsChange, error) {
	pid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	before, err := cursorPtr(after)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Events.PartyEthicsChange.ListByParty(ctx, pid, before, limitOf(first, 20))
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toPartyEthicsChange), nil
}

// WealthReports is the resolver for the wealthReports field.
func (r *partyResolver) WealthReports(ctx context.Context, obj *model.Party, from time.Time, to time.Time) ([]*model.EntityWealthReport, error) {
	if err := enforceTimeWindow(ctx, from, to, reportTimeWindowDays); err != nil {
		return nil, err
	}
	pid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Processed.Reports.EntityWealthReport.GetByEntityRange(ctx, "party", pid, from, to)
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toEntityWealthReport), nil
}

// MoneyCountryFlows is the resolver for the moneyCountryFlows field.
func (r *partyResolver) MoneyCountryFlows(ctx context.Context, obj *model.Party, from time.Time, to time.Time) ([]*model.MuCountryMoneyFlowReport, error) {
	panic(fmt.Errorf("not implemented: MoneyCountryFlows - moneyCountryFlows"))
}

// Country is the resolver for the country field.
func (r *regionResolver) Country(ctx context.Context, obj *model.Region) (*model.Country, error) {
	return loadCountry(ctx, obj.CountryID)
}

// InitialCountry is the resolver for the initialCountry field.
func (r *regionResolver) InitialCountry(ctx context.Context, obj *model.Region) (*model.Country, error) {
	return loadCountry(ctx, obj.InitialCountryID)
}

// Neighbors is the resolver for the neighbors field.
func (r *regionResolver) Neighbors(ctx context.Context, obj *model.Region) ([]*model.Region, error) {
	ids := make([]bson.ObjectID, 0, len(obj.NeighborIDs))
	for _, h := range obj.NeighborIDs {
		id, err := oidOf(h)
		if err != nil {
			return nil, err
		}
		ids = append(ids, id)
	}
	rows, err := r.Colls.Trackers.Region.GetMany(ctx, ids)
	if err != nil {
		return nil, err
	}
	return mapPtr(rows, toRegion), nil
}

// Parties is the resolver for the parties field.
func (r *regionResolver) Parties(ctx context.Context, obj *model.Region) ([]*model.Party, error) {
	rid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Trackers.Party.GetByRegion(ctx, rid)
	if err != nil {
		return nil, err
	}
	return mapPtr(rows, toParty), nil
}

// Mus is the resolver for the mus field.
func (r *regionResolver) Mus(ctx context.Context, obj *model.Region) ([]*model.Mu, error) {
	rid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Trackers.Mu.GetByRegion(ctx, rid)
	if err != nil {
		return nil, err
	}
	return mapPtr(rows, toMu), nil
}

// Companies is the resolver for the companies field.
func (r *regionResolver) Companies(ctx context.Context, obj *model.Region, first *int32, after *string) ([]*model.Company, error) {
	rid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	before, err := cursorPtr(after)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Trackers.Company.GetByRegionPaged(ctx, rid, before, limitOf(first, 20))
	if err != nil {
		return nil, err
	}
	return mapPtr(rows, toCompany), nil
}

// Battles is the resolver for the battles field.
func (r *regionResolver) Battles(ctx context.Context, obj *model.Region, first *int32, after *string, filter *model.BattleFilter) ([]*model.Battle, error) {
	rid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	before, err := cursorPtr(after)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Trackers.Battle.GetByRegionPaged(ctx, rid, toBattleFilter(filter), before, limitOf(first, 20))
	if err != nil {
		return nil, err
	}
	return mapPtr(rows, toBattle), nil
}

// ActiveBattles is the resolver for the activeBattles field.
func (r *regionResolver) ActiveBattles(ctx context.Context, obj *model.Region) ([]*model.Battle, error) {
	rid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	active := model.BattleFilterActive
	rows, err := r.Colls.Trackers.Battle.GetByRegionPaged(ctx, rid, toBattleFilter(&active), nil, 50)
	if err != nil {
		return nil, err
	}
	return mapPtr(rows, toBattle), nil
}

// OwnerHistory is the resolver for the ownerHistory field.
func (r *regionResolver) OwnerHistory(ctx context.Context, obj *model.Region, first *int32, after *string) ([]*model.RegionOwnerChange, error) {
	rid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	before, err := cursorPtr(after)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Events.RegionOwnerChange.ListByRegion(ctx, rid, before, limitOf(first, 20))
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toRegionOwnerChange), nil
}

// Deposits is the resolver for the deposits field.
func (r *regionResolver) Deposits(ctx context.Context, obj *model.Region, first *int32, after *string) ([]*model.RegionDeposit, error) {
	rid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	before, err := cursorPtr(after)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Events.RegionDeposit.ListByRegion(ctx, rid, before, limitOf(first, 20))
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toRegionDeposit), nil
}

// StrategicResources is the resolver for the strategicResources field.
func (r *regionResolver) StrategicResources(ctx context.Context, obj *model.Region, first *int32, after *string) ([]*model.RegionStrategicResource, error) {
	rid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	before, err := cursorPtr(after)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Events.RegionStrategicResource.ListByRegion(ctx, rid, before, limitOf(first, 20))
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toRegionStrategicResource), nil
}

// User is the resolver for the user field.
func (r *skillResolver) User(ctx context.Context, obj *model.Skill) (*model.User, error) {
	return loadUser(ctx, obj.UserID)
}

// User is the resolver for the user field.
func (r *tradeOfferResolver) User(ctx context.Context, obj *model.TradeOffer) (*model.User, error) {
	return loadUser(ctx, obj.UserID)
}

// Country is the resolver for the country field.
func (r *tradeOfferResolver) Country(ctx context.Context, obj *model.TradeOffer) (*model.Country, error) {
	return loadCountryP(ctx, obj.CountryID)
}

// Mu is the resolver for the mu field.
func (r *tradeOfferResolver) Mu(ctx context.Context, obj *model.TradeOffer) (*model.Mu, error) {
	return loadMuP(ctx, obj.MuID)
}

// Wealth is the resolver for the wealth field.
func (r *userResolver) Wealth(ctx context.Context, obj *model.User) ([]*model.FloatEntry, error) {
	return floatEntries(obj.WealthMap), nil
}

// Skills is the resolver for the skills field.
func (r *userResolver) Skills(ctx context.Context, obj *model.User) ([]*model.IntEntry, error) {
	return intEntries(obj.SkillsMap), nil
}

// Country is the resolver for the country field.
func (r *userResolver) Country(ctx context.Context, obj *model.User) (*model.Country, error) {
	return loadCountry(ctx, obj.CountryID)
}

// Company is the resolver for the company field.
func (r *userResolver) Company(ctx context.Context, obj *model.User) (*model.Company, error) {
	return loadCompanyP(ctx, obj.CompanyID)
}

// Party is the resolver for the party field.
func (r *userResolver) Party(ctx context.Context, obj *model.User) (*model.Party, error) {
	return loadPartyP(ctx, obj.PartyID)
}

// Mu is the resolver for the mu field.
func (r *userResolver) Mu(ctx context.Context, obj *model.User) (*model.Mu, error) {
	return loadMuP(ctx, obj.MuID)
}

// Transactions is the resolver for the transactions field.
func (r *userResolver) Transactions(ctx context.Context, obj *model.User, first *int32, after *string) (*model.ActivityConnection, error) {
	limit := limitOf(first, 20)
	uid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	before, err := cursorPtr(after)
	if err != nil {
		return nil, err
	}

	type edge struct {
		id  string
		act model.Activity
	}
	var edges []edge

	markets, err := r.Colls.Transactions.MarketTransaction.ByUser(ctx, uid, before, limit)
	if err != nil {
		return nil, err
	}
	for _, t := range markets {
		edges = append(edges, edge{t.ID.Hex(), toMarket(t)})
	}
	wages, err := r.Colls.Transactions.WageTransaction.ByUser(ctx, uid, before, limit)
	if err != nil {
		return nil, err
	}
	for _, t := range wages {
		edges = append(edges, edge{t.ID.Hex(), toWage(t)})
	}
	cases, err := r.Colls.Transactions.CaseTransaction.ByUser(ctx, uid, before, limit)
	if err != nil {
		return nil, err
	}
	for _, t := range cases {
		edges = append(edges, edge{t.ID.Hex(), toCase(t)})
	}
	trades, err := r.Colls.Transactions.TradeTransaction.ByUser(ctx, uid, before, limit)
	if err != nil {
		return nil, err
	}
	for _, t := range trades {
		edges = append(edges, edge{t.ID.Hex(), toTrade(t)})
	}
	crafts, err := r.Colls.Transactions.CraftTransaction.ByUser(ctx, uid, before, limit)
	if err != nil {
		return nil, err
	}
	for _, t := range crafts {
		edges = append(edges, edge{t.ID.Hex(), toCraft(t)})
	}
	dismantles, err := r.Colls.Transactions.DismantleTransaction.ByUser(ctx, uid, before, limit)
	if err != nil {
		return nil, err
	}
	for _, t := range dismantles {
		edges = append(edges, edge{t.ID.Hex(), toDismantle(t)})
	}
	loots, err := r.Colls.Transactions.LootTransaction.ByUser(ctx, uid, before, limit)
	if err != nil {
		return nil, err
	}
	for _, t := range loots {
		edges = append(edges, edge{t.ID.Hex(), toLoot(t)})
	}

	// ObjectID hex sorts lexicographically in timestamp order, so a descending
	// hex sort is a newest-first time sort across the merged collections.
	sort.Slice(edges, func(i, j int) bool { return edges[i].id > edges[j].id })

	more := len(edges) > limit
	if more {
		edges = edges[:limit]
	}
	conn := &model.ActivityConnection{
		Edges:       make([]model.Activity, len(edges)),
		HasNextPage: more,
	}
	for i, e := range edges {
		conn.Edges[i] = e.act
	}
	if len(edges) > 0 {
		cur := edges[len(edges)-1].id
		conn.EndCursor = &cur
	}
	return conn, nil
}

// Damages is the resolver for the damages field.
func (r *userResolver) Damages(ctx context.Context, obj *model.User, battleID string) ([]*model.Damage, error) {
	uid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	bid, err := oidOf(battleID)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Trackers.Damage.ByUserAndBattle(ctx, uid, bid)
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toDamage), nil
}

// AllDamages is the resolver for the allDamages field.
func (r *userResolver) AllDamages(ctx context.Context, obj *model.User, first *int32, after *string) ([]*model.Damage, error) {
	uid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	before, err := cursorPtr(after)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Trackers.Damage.GetByUserPaged(ctx, uid, before, limitOf(first, 20))
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toDamage), nil
}

// Battles is the resolver for the battles field.
func (r *userResolver) Battles(ctx context.Context, obj *model.User, first *int32, after *string) ([]*model.Battle, error) {
	uid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	before, err := cursorPtr(after)
	if err != nil {
		return nil, err
	}
	ids, err := r.Colls.Trackers.Damage.GetBattleIDsByUserPaged(ctx, uid, before, limitOf(first, 20))
	if err != nil {
		return nil, err
	}
	out := make([]*model.Battle, 0, len(ids))
	for _, id := range ids {
		b, err := loadBattle(ctx, id.Hex())
		if err != nil {
			return nil, err
		}
		if b != nil {
			out = append(out, b)
		}
	}
	return out, nil
}

// Items is the resolver for the items field.
func (r *userResolver) Items(ctx context.Context, obj *model.User, first *int32, after *string, status *enums.ItemStatus) ([]*model.Item, error) {
	uid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	before, err := cursorPtr(after)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Trackers.Item.GetByOwnerPaged(ctx, uid, before, limitOf(first, 20), status)
	if err != nil {
		return nil, err
	}
	return mapPtr(rows, toItem), nil
}

// OwnedCompanies is the resolver for the ownedCompanies field.
func (r *userResolver) OwnedCompanies(ctx context.Context, obj *model.User) ([]*model.Company, error) {
	uid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Trackers.Company.GetByUser(ctx, uid)
	if err != nil {
		return nil, err
	}
	return mapPtr(rows, toCompany), nil
}

// Employment is the resolver for the employment field.
func (r *userResolver) Employment(ctx context.Context, obj *model.User) (*model.Employee, error) {
	uid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	e, ok, err := r.Colls.Trackers.Employee.GetByUserID(ctx, uid)
	if err != nil || !ok {
		return nil, err
	}
	return toEmployee(e), nil
}

// TradeOffers is the resolver for the tradeOffers field.
func (r *userResolver) TradeOffers(ctx context.Context, obj *model.User, first *int32, after *string, itemCode *string, side *enums.TradeSide) ([]*model.TradeOffer, error) {
	uid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	before, err := cursorPtr(after)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Trackers.TradeOffer.GetByUserPaged(ctx, uid, before, limitOf(first, 20), itemCode, side)
	if err != nil {
		return nil, err
	}
	return mapPtr(rows, toTradeOffer), nil
}

// LatestSkills is the resolver for the latestSkills field.
func (r *userResolver) LatestSkills(ctx context.Context, obj *model.User) (*model.Skill, error) {
	uid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	s, err := r.Colls.Trackers.Skill.GetLatestForUser(ctx, uid)
	if err != nil {
		if errors.Is(err, mongo.ErrNoDocuments) {
			return nil, nil
		}
		return nil, err
	}
	return toSkill(s), nil
}

// SkillSnapshots is the resolver for the skillSnapshots field.
func (r *userResolver) SkillSnapshots(ctx context.Context, obj *model.User, first *int32, after *string) ([]*model.Skill, error) {
	uid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	before, err := cursorPtr(after)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Trackers.Skill.GetHistoryForUser(ctx, uid, before, limitOf(first, 20))
	if err != nil {
		return nil, err
	}
	return mapPtr(rows, toSkill), nil
}

// NameHistory is the resolver for the nameHistory field.
func (r *userResolver) NameHistory(ctx context.Context, obj *model.User, first *int32, after *string) ([]*model.UserNameChange, error) {
	uid, before, err := r.userCursor(obj, after)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Events.UserNameChange.ListByUser(ctx, uid, before, limitOf(first, 20))
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toUserNameChange), nil
}

// CountryHistory is the resolver for the countryHistory field.
func (r *userResolver) CountryHistory(ctx context.Context, obj *model.User, first *int32, after *string) ([]*model.UserCountryChange, error) {
	uid, before, err := r.userCursor(obj, after)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Events.UserCountryChange.ListByUser(ctx, uid, before, limitOf(first, 20))
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toUserCountryChange), nil
}

// PartyHistory is the resolver for the partyHistory field.
func (r *userResolver) PartyHistory(ctx context.Context, obj *model.User, first *int32, after *string) ([]*model.UserPartyChange, error) {
	uid, before, err := r.userCursor(obj, after)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Events.UserPartyChange.ListByUser(ctx, uid, before, limitOf(first, 20))
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toUserPartyChange), nil
}

// CompanyHistory is the resolver for the companyHistory field.
func (r *userResolver) CompanyHistory(ctx context.Context, obj *model.User, first *int32, after *string) ([]*model.UserCompanyChange, error) {
	uid, before, err := r.userCursor(obj, after)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Events.UserCompanyChange.ListByUser(ctx, uid, before, limitOf(first, 20))
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toUserCompanyChange), nil
}

// MuHistory is the resolver for the muHistory field.
func (r *userResolver) MuHistory(ctx context.Context, obj *model.User, first *int32, after *string) ([]*model.UserMuChange, error) {
	uid, before, err := r.userCursor(obj, after)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Events.UserMUChange.ListByUser(ctx, uid, before, limitOf(first, 20))
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toUserMuChange), nil
}

// SkillChangeHistory is the resolver for the skillChangeHistory field.
func (r *userResolver) SkillChangeHistory(ctx context.Context, obj *model.User, first *int32, after *string) ([]*model.UserSkillChange, error) {
	uid, before, err := r.userCursor(obj, after)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Events.UserSkillChange.ListByUser(ctx, uid, before, limitOf(first, 20))
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toUserSkillChange), nil
}

// WageHistory is the resolver for the wageHistory field.
func (r *userResolver) WageHistory(ctx context.Context, obj *model.User, first *int32, after *string) ([]*model.EmployeeWageChange, error) {
	uid, before, err := r.userCursor(obj, after)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Events.EmployeeWageChange.ListByUser(ctx, uid, before, limitOf(first, 20))
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toEmployeeWageChange), nil
}

// FinanceReports is the resolver for the financeReports field.
func (r *userResolver) FinanceReports(ctx context.Context, obj *model.User, from time.Time, to time.Time) ([]*model.UserFinanceReport, error) {
	if err := enforceTimeWindow(ctx, from, to, reportTimeWindowDays); err != nil {
		return nil, err
	}
	uid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Processed.Reports.UserFinanceReport.GetByUserRange(ctx, uid, from, to)
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toUserFinanceReport), nil
}

// FlipEvents is the resolver for the flipEvents field.
func (r *userResolver) FlipEvents(ctx context.Context, obj *model.User, from time.Time, to time.Time, first *int32, after *string) ([]*model.UserFlipEvent, error) {
	if err := enforceTimeWindow(ctx, from, to, rawTimeWindowDays); err != nil {
		return nil, err
	}
	uid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	before, err := cursorPtr(after)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Processed.Estimators.UserFlipEvent.GetByUserRange(ctx, uid, from, to, before, limitOf(first, 50))
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toUserFlipEvent), nil
}

// FlipState is the resolver for the flipState field.
func (r *userResolver) FlipState(ctx context.Context, obj *model.User) (*model.UserFlipState, error) {
	uid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	st, ok, err := r.Colls.Processed.Estimators.UserFlipState.Get(ctx, uid)
	if err != nil || !ok {
		return nil, err
	}
	return toUserFlipState(st), nil
}

// Inventory is the resolver for the inventory field.
func (r *userResolver) Inventory(ctx context.Context, obj *model.User) (*model.UserInventory, error) {
	uid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	inv, ok, err := r.Colls.Processed.Estimators.UserInventory.Get(ctx, uid)
	if err != nil || !ok {
		return nil, err
	}
	return toUserInventory(inv), nil
}

// BattleParticipation is the resolver for the battleParticipation field.
func (r *userResolver) BattleParticipation(ctx context.Context, obj *model.User) (*model.UserBattleParticipation, error) {
	uid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	p, ok, err := r.Colls.Processed.Estimators.BattleParticipation.Get(ctx, uid)
	if err != nil || !ok {
		return nil, err
	}
	return toUserBattleParticipation(p), nil
}

// Battle returns BattleResolver implementation.
func (r *Resolver) Battle() BattleResolver { return &battleResolver{r} }

// Company returns CompanyResolver implementation.
func (r *Resolver) Company() CompanyResolver { return &companyResolver{r} }

// Country returns CountryResolver implementation.
func (r *Resolver) Country() CountryResolver { return &countryResolver{r} }

// Damage returns DamageResolver implementation.
func (r *Resolver) Damage() DamageResolver { return &damageResolver{r} }

// Employee returns EmployeeResolver implementation.
func (r *Resolver) Employee() EmployeeResolver { return &employeeResolver{r} }

// Item returns ItemResolver implementation.
func (r *Resolver) Item() ItemResolver { return &itemResolver{r} }

// Mu returns MuResolver implementation.
func (r *Resolver) Mu() MuResolver { return &muResolver{r} }

// Party returns PartyResolver implementation.
func (r *Resolver) Party() PartyResolver { return &partyResolver{r} }

// Region returns RegionResolver implementation.
func (r *Resolver) Region() RegionResolver { return &regionResolver{r} }

// Skill returns SkillResolver implementation.
func (r *Resolver) Skill() SkillResolver { return &skillResolver{r} }

// TradeOffer returns TradeOfferResolver implementation.
func (r *Resolver) TradeOffer() TradeOfferResolver { return &tradeOfferResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type battleResolver struct{ *Resolver }
type companyResolver struct{ *Resolver }
type countryResolver struct{ *Resolver }
type damageResolver struct{ *Resolver }
type employeeResolver struct{ *Resolver }
type itemResolver struct{ *Resolver }
type muResolver struct{ *Resolver }
type partyResolver struct{ *Resolver }
type regionResolver struct{ *Resolver }
type skillResolver struct{ *Resolver }
type tradeOfferResolver struct{ *Resolver }
type userResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *muResolver) MoneyCountryFlows(ctx context.Context, obj *model.Mu, from time.Time, to time.Time) ([]*model.MuCountryMoneyFlowReport, error) {
	if err := enforceTimeWindow(ctx, from, to, reportTimeWindowDays); err != nil {
		return nil, err
	}
	mid, err := oidOf(obj.ID)
	if err != nil {
		return nil, err
	}
	rows, err := r.Colls.Processed.Reports.MuCountryMoneyFlow.GetByMuRange(ctx, mid, from, to)
	if err != nil {
		return nil, err
	}
	return mapVal(rows, toMuCountryMoneyFlowReport), nil
}
*/
