package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/warerastats/api/graph/model"
)

// Battle is the resolver for the battle field.
func (r *battleOrderChangeResolver) Battle(ctx context.Context, obj *model.BattleOrderChange) (*model.Battle, error) {
	return loadBattle(ctx, obj.BattleID)
}

// Entity is the resolver for the entity field.
func (r *battleOrderChangeResolver) Entity(ctx context.Context, obj *model.BattleOrderChange) (model.Entity, error) {
	return loadEntity(ctx, obj.Kind, obj.EntityID)
}

// Company is the resolver for the company field.
func (r *companyItemCodeChangeResolver) Company(ctx context.Context, obj *model.CompanyItemCodeChange) (*model.Company, error) {
	return loadCompany(ctx, obj.CompanyID)
}

// Company is the resolver for the company field.
func (r *companyRegionChangeResolver) Company(ctx context.Context, obj *model.CompanyRegionChange) (*model.Company, error) {
	return loadCompany(ctx, obj.CompanyID)
}

// Region is the resolver for the region field.
func (r *companyRegionChangeResolver) Region(ctx context.Context, obj *model.CompanyRegionChange) (*model.Region, error) {
	return loadRegion(ctx, obj.RegionID)
}

// Country is the resolver for the country field.
func (r *countryAllianceJoinResolver) Country(ctx context.Context, obj *model.CountryAllianceJoin) (*model.Country, error) {
	return loadCountry(ctx, obj.CountryID)
}

// Alliance is the resolver for the alliance field.
func (r *countryAllianceJoinResolver) Alliance(ctx context.Context, obj *model.CountryAllianceJoin) (*model.Alliance, error) {
	return loadAlliance(ctx, obj.AllianceID)
}

// Country is the resolver for the country field.
func (r *countryAllianceLeaveResolver) Country(ctx context.Context, obj *model.CountryAllianceLeave) (*model.Country, error) {
	return loadCountry(ctx, obj.CountryID)
}

// PrevAlliance is the resolver for the prevAlliance field.
func (r *countryAllianceLeaveResolver) PrevAlliance(ctx context.Context, obj *model.CountryAllianceLeave) (*model.Alliance, error) {
	return loadAllianceP(ctx, obj.PrevAllianceID)
}

// Country is the resolver for the country field.
func (r *countryRulingPartyChangeResolver) Country(ctx context.Context, obj *model.CountryRulingPartyChange) (*model.Country, error) {
	return loadCountry(ctx, obj.CountryID)
}

// Party is the resolver for the party field.
func (r *countryRulingPartyChangeResolver) Party(ctx context.Context, obj *model.CountryRulingPartyChange) (*model.Party, error) {
	return loadPartyP(ctx, obj.PartyID)
}

// Country is the resolver for the country field.
func (r *countrySpecialisationChangeResolver) Country(ctx context.Context, obj *model.CountrySpecialisationChange) (*model.Country, error) {
	return loadCountry(ctx, obj.CountryID)
}

// User is the resolver for the user field.
func (r *employeeWageChangeResolver) User(ctx context.Context, obj *model.EmployeeWageChange) (*model.User, error) {
	return loadUser(ctx, obj.UserID)
}

// Company is the resolver for the company field.
func (r *employeeWageChangeResolver) Company(ctx context.Context, obj *model.EmployeeWageChange) (*model.Company, error) {
	return loadCompany(ctx, obj.CompanyID)
}

// Mu is the resolver for the mu field.
func (r *muMercenaryReputationChangeResolver) Mu(ctx context.Context, obj *model.MuMercenaryReputationChange) (*model.Mu, error) {
	return loadMu(ctx, obj.MuID)
}

// Mu is the resolver for the mu field.
func (r *muNameChangeResolver) Mu(ctx context.Context, obj *model.MuNameChange) (*model.Mu, error) {
	return loadMu(ctx, obj.MuID)
}

// Mu is the resolver for the mu field.
func (r *muOwnerChangeResolver) Mu(ctx context.Context, obj *model.MuOwnerChange) (*model.Mu, error) {
	return loadMu(ctx, obj.MuID)
}

// Owner is the resolver for the owner field.
func (r *muOwnerChangeResolver) Owner(ctx context.Context, obj *model.MuOwnerChange) (*model.User, error) {
	return loadUser(ctx, obj.OwnerUserID)
}

// Party is the resolver for the party field.
func (r *partyDescriptionChangeResolver) Party(ctx context.Context, obj *model.PartyDescriptionChange) (*model.Party, error) {
	return loadParty(ctx, obj.PartyID)
}

// Party is the resolver for the party field.
func (r *partyEthicsChangeResolver) Party(ctx context.Context, obj *model.PartyEthicsChange) (*model.Party, error) {
	return loadParty(ctx, obj.PartyID)
}

// Party is the resolver for the party field.
func (r *partyLeaderChangeResolver) Party(ctx context.Context, obj *model.PartyLeaderChange) (*model.Party, error) {
	return loadParty(ctx, obj.PartyID)
}

// Leader is the resolver for the leader field.
func (r *partyLeaderChangeResolver) Leader(ctx context.Context, obj *model.PartyLeaderChange) (*model.User, error) {
	return loadUser(ctx, obj.LeaderUserID)
}

// Party is the resolver for the party field.
func (r *partyNameChangeResolver) Party(ctx context.Context, obj *model.PartyNameChange) (*model.Party, error) {
	return loadParty(ctx, obj.PartyID)
}

// Region is the resolver for the region field.
func (r *regionDepositResolver) Region(ctx context.Context, obj *model.RegionDeposit) (*model.Region, error) {
	return loadRegion(ctx, obj.RegionID)
}

// Region is the resolver for the region field.
func (r *regionOwnerChangeResolver) Region(ctx context.Context, obj *model.RegionOwnerChange) (*model.Region, error) {
	return loadRegion(ctx, obj.RegionID)
}

// Country is the resolver for the country field.
func (r *regionOwnerChangeResolver) Country(ctx context.Context, obj *model.RegionOwnerChange) (*model.Country, error) {
	return loadCountry(ctx, obj.CountryID)
}

// Region is the resolver for the region field.
func (r *regionStrategicResourceResolver) Region(ctx context.Context, obj *model.RegionStrategicResource) (*model.Region, error) {
	return loadRegion(ctx, obj.RegionID)
}

// User is the resolver for the user field.
func (r *userCompanyChangeResolver) User(ctx context.Context, obj *model.UserCompanyChange) (*model.User, error) {
	return loadUser(ctx, obj.UserID)
}

// Company is the resolver for the company field.
func (r *userCompanyChangeResolver) Company(ctx context.Context, obj *model.UserCompanyChange) (*model.Company, error) {
	return loadCompanyP(ctx, obj.CompanyID)
}

// User is the resolver for the user field.
func (r *userCountryChangeResolver) User(ctx context.Context, obj *model.UserCountryChange) (*model.User, error) {
	return loadUser(ctx, obj.UserID)
}

// Country is the resolver for the country field.
func (r *userCountryChangeResolver) Country(ctx context.Context, obj *model.UserCountryChange) (*model.Country, error) {
	return loadCountryP(ctx, obj.CountryID)
}

// User is the resolver for the user field.
func (r *userMuChangeResolver) User(ctx context.Context, obj *model.UserMuChange) (*model.User, error) {
	return loadUser(ctx, obj.UserID)
}

// Mu is the resolver for the mu field.
func (r *userMuChangeResolver) Mu(ctx context.Context, obj *model.UserMuChange) (*model.Mu, error) {
	return loadMuP(ctx, obj.MuID)
}

// User is the resolver for the user field.
func (r *userNameChangeResolver) User(ctx context.Context, obj *model.UserNameChange) (*model.User, error) {
	return loadUser(ctx, obj.UserID)
}

// User is the resolver for the user field.
func (r *userPartyChangeResolver) User(ctx context.Context, obj *model.UserPartyChange) (*model.User, error) {
	return loadUser(ctx, obj.UserID)
}

// Party is the resolver for the party field.
func (r *userPartyChangeResolver) Party(ctx context.Context, obj *model.UserPartyChange) (*model.Party, error) {
	return loadPartyP(ctx, obj.PartyID)
}

// User is the resolver for the user field.
func (r *userSkillChangeResolver) User(ctx context.Context, obj *model.UserSkillChange) (*model.User, error) {
	return loadUser(ctx, obj.UserID)
}

// Skills is the resolver for the skills field.
func (r *userSkillChangeResolver) Skills(ctx context.Context, obj *model.UserSkillChange) ([]*model.IntEntry, error) {
	return intEntries(obj.SkillsMap), nil
}

// BattleOrderChange returns BattleOrderChangeResolver implementation.
func (r *Resolver) BattleOrderChange() BattleOrderChangeResolver {
	return &battleOrderChangeResolver{r}
}

// CompanyItemCodeChange returns CompanyItemCodeChangeResolver implementation.
func (r *Resolver) CompanyItemCodeChange() CompanyItemCodeChangeResolver {
	return &companyItemCodeChangeResolver{r}
}

// CompanyRegionChange returns CompanyRegionChangeResolver implementation.
func (r *Resolver) CompanyRegionChange() CompanyRegionChangeResolver {
	return &companyRegionChangeResolver{r}
}

// CountryAllianceJoin returns CountryAllianceJoinResolver implementation.
func (r *Resolver) CountryAllianceJoin() CountryAllianceJoinResolver {
	return &countryAllianceJoinResolver{r}
}

// CountryAllianceLeave returns CountryAllianceLeaveResolver implementation.
func (r *Resolver) CountryAllianceLeave() CountryAllianceLeaveResolver {
	return &countryAllianceLeaveResolver{r}
}

// CountryRulingPartyChange returns CountryRulingPartyChangeResolver implementation.
func (r *Resolver) CountryRulingPartyChange() CountryRulingPartyChangeResolver {
	return &countryRulingPartyChangeResolver{r}
}

// CountrySpecialisationChange returns CountrySpecialisationChangeResolver implementation.
func (r *Resolver) CountrySpecialisationChange() CountrySpecialisationChangeResolver {
	return &countrySpecialisationChangeResolver{r}
}

// EmployeeWageChange returns EmployeeWageChangeResolver implementation.
func (r *Resolver) EmployeeWageChange() EmployeeWageChangeResolver {
	return &employeeWageChangeResolver{r}
}

// MuMercenaryReputationChange returns MuMercenaryReputationChangeResolver implementation.
func (r *Resolver) MuMercenaryReputationChange() MuMercenaryReputationChangeResolver {
	return &muMercenaryReputationChangeResolver{r}
}

// MuNameChange returns MuNameChangeResolver implementation.
func (r *Resolver) MuNameChange() MuNameChangeResolver { return &muNameChangeResolver{r} }

// MuOwnerChange returns MuOwnerChangeResolver implementation.
func (r *Resolver) MuOwnerChange() MuOwnerChangeResolver { return &muOwnerChangeResolver{r} }

// PartyDescriptionChange returns PartyDescriptionChangeResolver implementation.
func (r *Resolver) PartyDescriptionChange() PartyDescriptionChangeResolver {
	return &partyDescriptionChangeResolver{r}
}

// PartyEthicsChange returns PartyEthicsChangeResolver implementation.
func (r *Resolver) PartyEthicsChange() PartyEthicsChangeResolver {
	return &partyEthicsChangeResolver{r}
}

// PartyLeaderChange returns PartyLeaderChangeResolver implementation.
func (r *Resolver) PartyLeaderChange() PartyLeaderChangeResolver {
	return &partyLeaderChangeResolver{r}
}

// PartyNameChange returns PartyNameChangeResolver implementation.
func (r *Resolver) PartyNameChange() PartyNameChangeResolver { return &partyNameChangeResolver{r} }

// RegionDeposit returns RegionDepositResolver implementation.
func (r *Resolver) RegionDeposit() RegionDepositResolver { return &regionDepositResolver{r} }

// RegionOwnerChange returns RegionOwnerChangeResolver implementation.
func (r *Resolver) RegionOwnerChange() RegionOwnerChangeResolver {
	return &regionOwnerChangeResolver{r}
}

// RegionStrategicResource returns RegionStrategicResourceResolver implementation.
func (r *Resolver) RegionStrategicResource() RegionStrategicResourceResolver {
	return &regionStrategicResourceResolver{r}
}

// UserCompanyChange returns UserCompanyChangeResolver implementation.
func (r *Resolver) UserCompanyChange() UserCompanyChangeResolver {
	return &userCompanyChangeResolver{r}
}

// UserCountryChange returns UserCountryChangeResolver implementation.
func (r *Resolver) UserCountryChange() UserCountryChangeResolver {
	return &userCountryChangeResolver{r}
}

// UserMuChange returns UserMuChangeResolver implementation.
func (r *Resolver) UserMuChange() UserMuChangeResolver { return &userMuChangeResolver{r} }

// UserNameChange returns UserNameChangeResolver implementation.
func (r *Resolver) UserNameChange() UserNameChangeResolver { return &userNameChangeResolver{r} }

// UserPartyChange returns UserPartyChangeResolver implementation.
func (r *Resolver) UserPartyChange() UserPartyChangeResolver { return &userPartyChangeResolver{r} }

// UserSkillChange returns UserSkillChangeResolver implementation.
func (r *Resolver) UserSkillChange() UserSkillChangeResolver { return &userSkillChangeResolver{r} }

type battleOrderChangeResolver struct{ *Resolver }
type companyItemCodeChangeResolver struct{ *Resolver }
type companyRegionChangeResolver struct{ *Resolver }
type countryAllianceJoinResolver struct{ *Resolver }
type countryAllianceLeaveResolver struct{ *Resolver }
type countryRulingPartyChangeResolver struct{ *Resolver }
type countrySpecialisationChangeResolver struct{ *Resolver }
type employeeWageChangeResolver struct{ *Resolver }
type muMercenaryReputationChangeResolver struct{ *Resolver }
type muNameChangeResolver struct{ *Resolver }
type muOwnerChangeResolver struct{ *Resolver }
type partyDescriptionChangeResolver struct{ *Resolver }
type partyEthicsChangeResolver struct{ *Resolver }
type partyLeaderChangeResolver struct{ *Resolver }
type partyNameChangeResolver struct{ *Resolver }
type regionDepositResolver struct{ *Resolver }
type regionOwnerChangeResolver struct{ *Resolver }
type regionStrategicResourceResolver struct{ *Resolver }
type userCompanyChangeResolver struct{ *Resolver }
type userCountryChangeResolver struct{ *Resolver }
type userMuChangeResolver struct{ *Resolver }
type userNameChangeResolver struct{ *Resolver }
type userPartyChangeResolver struct{ *Resolver }
type userSkillChangeResolver struct{ *Resolver }
