package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/warerastats/api/graph/model"
)

// Alliance is the resolver for the alliance field.
func (r *allianceMoneyFlowCounterpartResolver) Alliance(ctx context.Context, obj *model.AllianceMoneyFlowCounterpart) (*model.Alliance, error) {
	return loadAlliance(ctx, obj.AllianceID)
}

// Alliance is the resolver for the alliance field.
func (r *allianceMoneyFlowReportResolver) Alliance(ctx context.Context, obj *model.AllianceMoneyFlowReport) (*model.Alliance, error) {
	return loadAlliance(ctx, obj.AllianceID)
}

// Battle is the resolver for the battle field.
func (r *battleDamageReportResolver) Battle(ctx context.Context, obj *model.BattleDamageReport) (*model.Battle, error) {
	return loadBattle(ctx, obj.BattleID)
}

// Entity is the resolver for the entity field.
func (r *battleDamageReportResolver) Entity(ctx context.Context, obj *model.BattleDamageReport) (model.Entity, error) {
	return loadEntity(ctx, obj.EntityType, obj.EntityID)
}

// Alliance is the resolver for the alliance field.
func (r *countryAllianceMoneyFlowCounterpartResolver) Alliance(ctx context.Context, obj *model.CountryAllianceMoneyFlowCounterpart) (*model.Alliance, error) {
	return loadAlliance(ctx, obj.AllianceID)
}

// Country is the resolver for the country field.
func (r *countryAllianceMoneyFlowReportResolver) Country(ctx context.Context, obj *model.CountryAllianceMoneyFlowReport) (*model.Country, error) {
	return loadCountry(ctx, obj.CountryID)
}

// Country is the resolver for the country field.
func (r *countryFlipEventResolver) Country(ctx context.Context, obj *model.CountryFlipEvent) (*model.Country, error) {
	return loadCountry(ctx, obj.CountryID)
}

// Country is the resolver for the country field.
func (r *countryFlipStateResolver) Country(ctx context.Context, obj *model.CountryFlipState) (*model.Country, error) {
	return loadCountry(ctx, obj.CountryID)
}

// Lots is the resolver for the lots field.
func (r *countryInventoryResolver) Lots(ctx context.Context, obj *model.CountryInventory) ([]*model.InventoryLotGroup, error) {
	out := make([]*model.InventoryLotGroup, 0, len(obj.LotsMap))
	for code, lots := range obj.LotsMap {
		group := &model.InventoryLotGroup{ItemCode: code, Lots: make([]*model.InventoryLot, len(lots))}
		for i := range lots {
			l := lots[i]
			group.Lots[i] = &l
		}
		out = append(out, group)
	}
	return out, nil
}

// Country is the resolver for the country field.
func (r *countryInventoryResolver) Country(ctx context.Context, obj *model.CountryInventory) (*model.Country, error) {
	return loadCountry(ctx, obj.CountryID)
}

// Country is the resolver for the country field.
func (r *countryMoneyFlowCounterpartResolver) Country(ctx context.Context, obj *model.CountryMoneyFlowCounterpart) (*model.Country, error) {
	return loadCountry(ctx, obj.CountryID)
}

// Country is the resolver for the country field.
func (r *countryMoneyFlowReportResolver) Country(ctx context.Context, obj *model.CountryMoneyFlowReport) (*model.Country, error) {
	return loadCountry(ctx, obj.CountryID)
}

// Country is the resolver for the country field.
func (r *countryTaxFlowResolver) Country(ctx context.Context, obj *model.CountryTaxFlow) (*model.Country, error) {
	return loadCountry(ctx, obj.CountryID)
}

// Entity is the resolver for the entity field.
func (r *entityWealthReportResolver) Entity(ctx context.Context, obj *model.EntityWealthReport) (model.Entity, error) {
	return loadEntity(ctx, obj.EntityType, obj.EntityID)
}

// PctChange24h is the resolver for the pctChange24h field.
func (r *inflationPointResolver) PctChange24h(ctx context.Context, obj *model.InflationPoint) (float64, error) {
	return obj.PctChange, nil
}

// Alliance is the resolver for the alliance field.
func (r *muAllianceMoneyFlowCounterpartResolver) Alliance(ctx context.Context, obj *model.MuAllianceMoneyFlowCounterpart) (*model.Alliance, error) {
	return loadAlliance(ctx, obj.AllianceID)
}

// Mu is the resolver for the mu field.
func (r *muAllianceMoneyFlowReportResolver) Mu(ctx context.Context, obj *model.MuAllianceMoneyFlowReport) (*model.Mu, error) {
	return loadMu(ctx, obj.MuID)
}

// Country is the resolver for the country field.
func (r *muCountryMoneyFlowCounterpartResolver) Country(ctx context.Context, obj *model.MuCountryMoneyFlowCounterpart) (*model.Country, error) {
	return loadCountry(ctx, obj.CountryID)
}

// Mu is the resolver for the mu field.
func (r *muCountryMoneyFlowReportResolver) Mu(ctx context.Context, obj *model.MuCountryMoneyFlowReport) (*model.Mu, error) {
	return loadMu(ctx, obj.MuID)
}

// Country is the resolver for the country field.
func (r *partyMoneyFlowCounterpartResolver) Country(ctx context.Context, obj *model.PartyMoneyFlowCounterpart) (*model.Country, error) {
	return loadCountry(ctx, obj.CountryID)
}

// Party is the resolver for the party field.
func (r *partyMoneyFlowReportResolver) Party(ctx context.Context, obj *model.PartyMoneyFlowReport) (*model.Party, error) {
	return loadParty(ctx, obj.PartyID)
}

// Country is the resolver for the country field.
func (r *taxHijackResolver) Country(ctx context.Context, obj *model.TaxHijack) (*model.Country, error) {
	return loadCountry(ctx, obj.CountryID)
}

// Country is the resolver for the country field.
func (r *taxSourceResolver) Country(ctx context.Context, obj *model.TaxSource) (*model.Country, error) {
	return loadCountry(ctx, obj.CountryID)
}

// User is the resolver for the user field.
func (r *userBattleParticipationResolver) User(ctx context.Context, obj *model.UserBattleParticipation) (*model.User, error) {
	return loadUser(ctx, obj.UserID)
}

// User is the resolver for the user field.
func (r *userFinanceReportResolver) User(ctx context.Context, obj *model.UserFinanceReport) (*model.User, error) {
	return loadUser(ctx, obj.UserID)
}

// User is the resolver for the user field.
func (r *userFlipEventResolver) User(ctx context.Context, obj *model.UserFlipEvent) (*model.User, error) {
	return loadUser(ctx, obj.UserID)
}

// OpenLots is the resolver for the openLots field.
func (r *userFlipStateResolver) OpenLots(ctx context.Context, obj *model.UserFlipState) ([]*model.FlipLotGroup, error) {
	out := make([]*model.FlipLotGroup, 0, len(obj.OpenLotsMap))
	for code, lots := range obj.OpenLotsMap {
		group := &model.FlipLotGroup{ItemCode: code, Lots: make([]*model.FlipLot, len(lots))}
		for i := range lots {
			l := lots[i]
			group.Lots[i] = &l
		}
		out = append(out, group)
	}
	return out, nil
}

// User is the resolver for the user field.
func (r *userFlipStateResolver) User(ctx context.Context, obj *model.UserFlipState) (*model.User, error) {
	return loadUser(ctx, obj.UserID)
}

// Items is the resolver for the items field.
func (r *userInventoryResolver) Items(ctx context.Context, obj *model.UserInventory) ([]*model.IntEntry, error) {
	return intEntries(obj.ItemsMap), nil
}

// User is the resolver for the user field.
func (r *userInventoryResolver) User(ctx context.Context, obj *model.UserInventory) (*model.User, error) {
	return loadUser(ctx, obj.UserID)
}

// User is the resolver for the user field.
func (r *wagePaidUserResolver) User(ctx context.Context, obj *model.WagePaidUser) (*model.User, error) {
	return loadUser(ctx, obj.UserID)
}

// AllianceMoneyFlowCounterpart returns AllianceMoneyFlowCounterpartResolver implementation.
func (r *Resolver) AllianceMoneyFlowCounterpart() AllianceMoneyFlowCounterpartResolver {
	return &allianceMoneyFlowCounterpartResolver{r}
}

// AllianceMoneyFlowReport returns AllianceMoneyFlowReportResolver implementation.
func (r *Resolver) AllianceMoneyFlowReport() AllianceMoneyFlowReportResolver {
	return &allianceMoneyFlowReportResolver{r}
}

// BattleDamageReport returns BattleDamageReportResolver implementation.
func (r *Resolver) BattleDamageReport() BattleDamageReportResolver {
	return &battleDamageReportResolver{r}
}

// CountryAllianceMoneyFlowCounterpart returns CountryAllianceMoneyFlowCounterpartResolver implementation.
func (r *Resolver) CountryAllianceMoneyFlowCounterpart() CountryAllianceMoneyFlowCounterpartResolver {
	return &countryAllianceMoneyFlowCounterpartResolver{r}
}

// CountryAllianceMoneyFlowReport returns CountryAllianceMoneyFlowReportResolver implementation.
func (r *Resolver) CountryAllianceMoneyFlowReport() CountryAllianceMoneyFlowReportResolver {
	return &countryAllianceMoneyFlowReportResolver{r}
}

// CountryFlipEvent returns CountryFlipEventResolver implementation.
func (r *Resolver) CountryFlipEvent() CountryFlipEventResolver { return &countryFlipEventResolver{r} }

// CountryFlipState returns CountryFlipStateResolver implementation.
func (r *Resolver) CountryFlipState() CountryFlipStateResolver { return &countryFlipStateResolver{r} }

// CountryInventory returns CountryInventoryResolver implementation.
func (r *Resolver) CountryInventory() CountryInventoryResolver { return &countryInventoryResolver{r} }

// CountryMoneyFlowCounterpart returns CountryMoneyFlowCounterpartResolver implementation.
func (r *Resolver) CountryMoneyFlowCounterpart() CountryMoneyFlowCounterpartResolver {
	return &countryMoneyFlowCounterpartResolver{r}
}

// CountryMoneyFlowReport returns CountryMoneyFlowReportResolver implementation.
func (r *Resolver) CountryMoneyFlowReport() CountryMoneyFlowReportResolver {
	return &countryMoneyFlowReportResolver{r}
}

// CountryTaxFlow returns CountryTaxFlowResolver implementation.
func (r *Resolver) CountryTaxFlow() CountryTaxFlowResolver { return &countryTaxFlowResolver{r} }

// EntityWealthReport returns EntityWealthReportResolver implementation.
func (r *Resolver) EntityWealthReport() EntityWealthReportResolver {
	return &entityWealthReportResolver{r}
}

// InflationPoint returns InflationPointResolver implementation.
func (r *Resolver) InflationPoint() InflationPointResolver { return &inflationPointResolver{r} }

// MuAllianceMoneyFlowCounterpart returns MuAllianceMoneyFlowCounterpartResolver implementation.
func (r *Resolver) MuAllianceMoneyFlowCounterpart() MuAllianceMoneyFlowCounterpartResolver {
	return &muAllianceMoneyFlowCounterpartResolver{r}
}

// MuAllianceMoneyFlowReport returns MuAllianceMoneyFlowReportResolver implementation.
func (r *Resolver) MuAllianceMoneyFlowReport() MuAllianceMoneyFlowReportResolver {
	return &muAllianceMoneyFlowReportResolver{r}
}

// MuCountryMoneyFlowCounterpart returns MuCountryMoneyFlowCounterpartResolver implementation.
func (r *Resolver) MuCountryMoneyFlowCounterpart() MuCountryMoneyFlowCounterpartResolver {
	return &muCountryMoneyFlowCounterpartResolver{r}
}

// MuCountryMoneyFlowReport returns MuCountryMoneyFlowReportResolver implementation.
func (r *Resolver) MuCountryMoneyFlowReport() MuCountryMoneyFlowReportResolver {
	return &muCountryMoneyFlowReportResolver{r}
}

// PartyMoneyFlowCounterpart returns PartyMoneyFlowCounterpartResolver implementation.
func (r *Resolver) PartyMoneyFlowCounterpart() PartyMoneyFlowCounterpartResolver {
	return &partyMoneyFlowCounterpartResolver{r}
}

// PartyMoneyFlowReport returns PartyMoneyFlowReportResolver implementation.
func (r *Resolver) PartyMoneyFlowReport() PartyMoneyFlowReportResolver {
	return &partyMoneyFlowReportResolver{r}
}

// TaxHijack returns TaxHijackResolver implementation.
func (r *Resolver) TaxHijack() TaxHijackResolver { return &taxHijackResolver{r} }

// TaxSource returns TaxSourceResolver implementation.
func (r *Resolver) TaxSource() TaxSourceResolver { return &taxSourceResolver{r} }

// UserBattleParticipation returns UserBattleParticipationResolver implementation.
func (r *Resolver) UserBattleParticipation() UserBattleParticipationResolver {
	return &userBattleParticipationResolver{r}
}

// UserFinanceReport returns UserFinanceReportResolver implementation.
func (r *Resolver) UserFinanceReport() UserFinanceReportResolver {
	return &userFinanceReportResolver{r}
}

// UserFlipEvent returns UserFlipEventResolver implementation.
func (r *Resolver) UserFlipEvent() UserFlipEventResolver { return &userFlipEventResolver{r} }

// UserFlipState returns UserFlipStateResolver implementation.
func (r *Resolver) UserFlipState() UserFlipStateResolver { return &userFlipStateResolver{r} }

// UserInventory returns UserInventoryResolver implementation.
func (r *Resolver) UserInventory() UserInventoryResolver { return &userInventoryResolver{r} }

// WagePaidUser returns WagePaidUserResolver implementation.
func (r *Resolver) WagePaidUser() WagePaidUserResolver { return &wagePaidUserResolver{r} }

type allianceMoneyFlowCounterpartResolver struct{ *Resolver }
type allianceMoneyFlowReportResolver struct{ *Resolver }
type battleDamageReportResolver struct{ *Resolver }
type countryAllianceMoneyFlowCounterpartResolver struct{ *Resolver }
type countryAllianceMoneyFlowReportResolver struct{ *Resolver }
type countryFlipEventResolver struct{ *Resolver }
type countryFlipStateResolver struct{ *Resolver }
type countryInventoryResolver struct{ *Resolver }
type countryMoneyFlowCounterpartResolver struct{ *Resolver }
type countryMoneyFlowReportResolver struct{ *Resolver }
type countryTaxFlowResolver struct{ *Resolver }
type entityWealthReportResolver struct{ *Resolver }
type inflationPointResolver struct{ *Resolver }
type muAllianceMoneyFlowCounterpartResolver struct{ *Resolver }
type muAllianceMoneyFlowReportResolver struct{ *Resolver }
type muCountryMoneyFlowCounterpartResolver struct{ *Resolver }
type muCountryMoneyFlowReportResolver struct{ *Resolver }
type partyMoneyFlowCounterpartResolver struct{ *Resolver }
type partyMoneyFlowReportResolver struct{ *Resolver }
type taxHijackResolver struct{ *Resolver }
type taxSourceResolver struct{ *Resolver }
type userBattleParticipationResolver struct{ *Resolver }
type userFinanceReportResolver struct{ *Resolver }
type userFlipEventResolver struct{ *Resolver }
type userFlipStateResolver struct{ *Resolver }
type userInventoryResolver struct{ *Resolver }
type wagePaidUserResolver struct{ *Resolver }
