// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type PartyBattleParticipation struct {
	Party       *Party `json:"party"`
	TotalDamage int    `json:"totalDamage"`
	BattleCount int32  `json:"battleCount"`
}

type Query struct {
}

type BattleFilter string

const (
	BattleFilterAll       BattleFilter = "ALL"
	BattleFilterActive    BattleFilter = "ACTIVE"
	BattleFilterFinalized BattleFilter = "FINALIZED"
)

var AllBattleFilter = []BattleFilter{
	BattleFilterAll,
	BattleFilterActive,
	BattleFilterFinalized,
}

func (e BattleFilter) IsValid() bool {
	switch e {
	case BattleFilterAll, BattleFilterActive, BattleFilterFinalized:
		return true
	}
	return false
}

func (e BattleFilter) String() string {
	return string(e)
}

func (e *BattleFilter) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BattleFilter(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BattleFilter", str)
	}
	return nil
}

func (e BattleFilter) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BattleFilter) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BattleFilter) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type EntityKind string

const (
	EntityKindUser     EntityKind = "USER"
	EntityKindCountry  EntityKind = "COUNTRY"
	EntityKindParty    EntityKind = "PARTY"
	EntityKindMu       EntityKind = "MU"
	EntityKindAlliance EntityKind = "ALLIANCE"
	EntityKindSide     EntityKind = "SIDE"
)

var AllEntityKind = []EntityKind{
	EntityKindUser,
	EntityKindCountry,
	EntityKindParty,
	EntityKindMu,
	EntityKindAlliance,
	EntityKindSide,
}

func (e EntityKind) IsValid() bool {
	switch e {
	case EntityKindUser, EntityKindCountry, EntityKindParty, EntityKindMu, EntityKindAlliance, EntityKindSide:
		return true
	}
	return false
}

func (e EntityKind) String() string {
	return string(e)
}

func (e *EntityKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = EntityKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid EntityKind", str)
	}
	return nil
}

func (e EntityKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *EntityKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e EntityKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
